"""
==============================================================
PhonePe Transaction Insights — Streamlit Dashboard
Run with: streamlit run phonepe_dashboard.py
CSVs must be in ./phonepe_csvs/ (generated by phonepe_json_to_csv.py)
==============================================================
"""

import os
import warnings
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import streamlit as st

warnings.filterwarnings("ignore")

# ─────────────────────────────────────────────────────────────
#  PAGE CONFIG
# ─────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="PhonePe Transaction Insights",
    page_icon="📱",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─────────────────────────────────────────────────────────────
#  CUSTOM CSS
# ─────────────────────────────────────────────────────────────
st.markdown("""
<style>
  [data-testid="stAppViewContainer"] { background: #0f0e17; }
  [data-testid="stSidebar"] { background: #1a1a2e; }
  .metric-card {
      background: linear-gradient(135deg,#6c3fbd,#a855f7);
      border-radius:12px; padding:18px; text-align:center;
      color:#fff; margin:4px;
  }
  .metric-value { font-size:2rem; font-weight:700; }
  .metric-label { font-size:.85rem; opacity:.85; margin-top:4px; }
  .section-header {
      font-size:1.5rem; font-weight:700; color:#c084fc;
      border-left:4px solid #a855f7; padding-left:10px;
      margin: 20px 0 12px 0;
  }
  h1 { color:#e2c7ff !important; }
  h2,h3 { color:#c084fc !important; }
  .stSelectbox label, .stMultiSelect label { color:#c084fc; }
</style>
""", unsafe_allow_html=True)

CSV_DIR = "phonepe_csvs"

# ─────────────────────────────────────────────────────────────
#  DATA LOADER
# ─────────────────────────────────────────────────────────────
@st.cache_data
def load(name):
    path = os.path.join(CSV_DIR, f"{name}.csv")
    if os.path.exists(path):
        return pd.read_csv(path)
    return pd.DataFrame()

def fmt_cr(val):
    """Format large numbers as ₹ Cr or ₹ Lakh."""
    if val >= 1e7:
        return f"₹{val/1e7:.2f} Cr"
    elif val >= 1e5:
        return f"₹{val/1e5:.2f} L"
    return f"₹{val:,.0f}"

def fmt_num(val):
    if val >= 1e9:
        return f"{val/1e9:.2f}B"
    elif val >= 1e6:
        return f"{val/1e6:.2f}M"
    elif val >= 1e3:
        return f"{val/1e3:.2f}K"
    return f"{val:,.0f}"

PURPLE = px.colors.sequential.Purples
PLOTLY_THEME = dict(
    plot_bgcolor="#0f0e17",
    paper_bgcolor="#0f0e17",
    font_color="#e2c7ff",
    colorway=["#a855f7","#7c3aed","#c084fc","#6d28d9","#d8b4fe","#4c1d95","#f5d0fe"],
)

def styled_fig(fig):
    fig.update_layout(**PLOTLY_THEME)
    return fig

# ─────────────────────────────────────────────────────────────
#  SIDEBAR
# ─────────────────────────────────────────────────────────────
with st.sidebar:
    st.image("https://upload.wikimedia.org/wikipedia/commons/7/71/PhonePe_Logo.png", width=160)
    st.markdown("### 🔎 Filters")
    agg_txn = load("aggregated_transaction")
    years_avail = sorted(agg_txn["Year"].unique()) if not agg_txn.empty else [2018,2019,2020,2021,2022,2023]
    sel_years = st.multiselect("Year(s)", years_avail, default=years_avail)
    sel_quarters = st.multiselect("Quarter(s)", [1,2,3,4], default=[1,2,3,4])
    states_avail = sorted(agg_txn["State"].unique()) if not agg_txn.empty else []
    sel_states = st.multiselect("State(s) — leave blank for ALL", states_avail)

    st.markdown("---")
    page = st.radio("📊 Dashboard", [
        "🏠 Overview",
        "💳 Transactions",
        "👥 Users",
        "🛡️ Insurance",
        "🗺️ Geo Maps",
        "🏆 Top Performers",
        "📈 Trend Analysis",
    ])

# ─────────────────────────────────────────────────────────────
#  APPLY FILTERS
# ─────────────────────────────────────────────────────────────
def apply_filters(df):
    if df.empty:
        return df
    if sel_years and "Year" in df.columns:
        df = df[df["Year"].isin(sel_years)]
    if sel_quarters and "Quarter" in df.columns:
        df = df[df["Quarter"].isin(sel_quarters)]
    if sel_states and "State" in df.columns:
        df = df[df["State"].isin(sel_states)]
    return df

# ─────────────────────────────────────────────────────────────
#  PAGE: OVERVIEW
# ─────────────────────────────────────────────────────────────
if page == "🏠 Overview":
    st.markdown("# 📱 PhonePe Transaction Insights")
    st.markdown("**Labmentix Data Science Internship Project** — Comprehensive analysis of PhonePe Pulse data")
    st.markdown("---")

    agg_txn = apply_filters(load("aggregated_transaction"))
    agg_usr = apply_filters(load("aggregated_user"))
    agg_ins = apply_filters(load("aggregated_insurance"))

    total_txn_amount = agg_txn["Transaction_Amount"].sum() if not agg_txn.empty else 0
    total_txn_count  = agg_txn["Transaction_Count"].sum()  if not agg_txn.empty else 0
    total_users      = agg_usr["Registered_Users"].max()   if not agg_usr.empty else 0
    total_ins_amount = agg_ins["Transaction_Amount"].sum() if not agg_ins.empty else 0

    c1,c2,c3,c4 = st.columns(4)
    for col, label, val in zip(
        [c1,c2,c3,c4],
        ["💰 Total Transaction Value","🔢 Total Transactions","👤 Peak Registered Users","🛡️ Insurance Value"],
        [fmt_cr(total_txn_amount), fmt_num(total_txn_count), fmt_num(total_users), fmt_cr(total_ins_amount)]
    ):
        col.markdown(f"""<div class="metric-card">
            <div class="metric-value">{val}</div>
            <div class="metric-label">{label}</div></div>""", unsafe_allow_html=True)

    st.markdown("---")
    # --- YoY Transaction Volume ---
    if not agg_txn.empty:
        st.markdown('<div class="section-header">📅 Yearly Transaction Trends</div>', unsafe_allow_html=True)
        yoy = agg_txn.groupby("Year").agg(
            Amount=("Transaction_Amount","sum"),
            Count=("Transaction_Count","sum")
        ).reset_index()
        fig = make_subplots(specs=[[{"secondary_y": True}]])
        fig.add_trace(go.Bar(x=yoy["Year"], y=yoy["Amount"], name="Amount (₹)",
                             marker_color="#a855f7"), secondary_y=False)
        fig.add_trace(go.Scatter(x=yoy["Year"], y=yoy["Count"], name="Count",
                                 mode="lines+markers", line=dict(color="#f5d0fe",width=2)), secondary_y=True)
        fig.update_layout(title="Year-on-Year Transaction Amount & Count", **PLOTLY_THEME)
        st.plotly_chart(fig, use_container_width=True)

    # --- Transaction Type Share ---
    if not agg_txn.empty:
        col1, col2 = st.columns(2)
        with col1:
            st.markdown('<div class="section-header">💳 Transaction Type Split</div>', unsafe_allow_html=True)
            type_data = agg_txn.groupby("Transaction_Type")["Transaction_Amount"].sum().reset_index()
            fig = px.pie(type_data, names="Transaction_Type", values="Transaction_Amount",
                         hole=0.4, color_discrete_sequence=["#a855f7","#7c3aed","#c084fc","#6d28d9","#d8b4fe"])
            fig.update_layout(**PLOTLY_THEME)
            st.plotly_chart(fig, use_container_width=True)
        with col2:
            st.markdown('<div class="section-header">📊 Top 10 States by Volume</div>', unsafe_allow_html=True)
            top_states = agg_txn.groupby("State")["Transaction_Amount"].sum().nlargest(10).reset_index()
            fig = px.bar(top_states, x="Transaction_Amount", y="State", orientation="h",
                         color="Transaction_Amount", color_continuous_scale="Purples")
            fig.update_layout(**PLOTLY_THEME)
            st.plotly_chart(fig, use_container_width=True)


# ─────────────────────────────────────────────────────────────
#  PAGE: TRANSACTIONS
# ─────────────────────────────────────────────────────────────
elif page == "💳 Transactions":
    st.markdown("# 💳 Transaction Analysis")
    agg_txn = apply_filters(load("aggregated_transaction"))
    if agg_txn.empty:
        st.warning("No transaction data found. Run the JSON→CSV converter first.")
    else:
        # 1. Quarterly heatmap
        st.markdown('<div class="section-header">🌡️ Quarterly Transaction Heatmap (by State)</div>', unsafe_allow_html=True)
        pivot = agg_txn.pivot_table(index="State", columns="Quarter",
                                    values="Transaction_Amount", aggfunc="sum").fillna(0)
        fig = px.imshow(pivot, color_continuous_scale="Purples",
                        labels=dict(x="Quarter", y="State", color="Amount (₹)"))
        fig.update_layout(**PLOTLY_THEME, height=700)
        st.plotly_chart(fig, use_container_width=True)

        col1, col2 = st.columns(2)
        with col1:
            # 2. Transaction type by year grouped bar
            st.markdown('<div class="section-header">📊 Transaction Type by Year</div>', unsafe_allow_html=True)
            t_year = agg_txn.groupby(["Year","Transaction_Type"])["Transaction_Count"].sum().reset_index()
            fig = px.bar(t_year, x="Year", y="Transaction_Count", color="Transaction_Type",
                         barmode="group", color_discrete_sequence=["#a855f7","#7c3aed","#c084fc","#6d28d9","#d8b4fe"])
            fig.update_layout(**PLOTLY_THEME)
            st.plotly_chart(fig, use_container_width=True)

        with col2:
            # 3. Avg transaction value per type
            st.markdown('<div class="section-header">💰 Avg Transaction Value by Type</div>', unsafe_allow_html=True)
            avg_val = agg_txn.copy()
            avg_val["Avg_Value"] = avg_val["Transaction_Amount"] / avg_val["Transaction_Count"].replace(0,np.nan)
            avg_val = avg_val.groupby("Transaction_Type")["Avg_Value"].mean().reset_index()
            fig = px.bar(avg_val, x="Transaction_Type", y="Avg_Value",
                         color="Avg_Value", color_continuous_scale="Purples")
            fig.update_layout(**PLOTLY_THEME)
            st.plotly_chart(fig, use_container_width=True)

        # 4. Quarterly trend line per state (top 5)
        st.markdown('<div class="section-header">📈 Quarterly Trend — Top 5 States</div>', unsafe_allow_html=True)
        top5 = agg_txn.groupby("State")["Transaction_Amount"].sum().nlargest(5).index.tolist()
        trend_df = agg_txn[agg_txn["State"].isin(top5)].copy()
        trend_df["Period"] = trend_df["Year"].astype(str) + " Q" + trend_df["Quarter"].astype(str)
        trend_line = trend_df.groupby(["Period","State"])["Transaction_Amount"].sum().reset_index()
        trend_line = trend_line.sort_values("Period")
        fig = px.line(trend_line, x="Period", y="Transaction_Amount", color="State",
                      markers=True, color_discrete_sequence=["#a855f7","#7c3aed","#c084fc","#6d28d9","#d8b4fe"])
        fig.update_layout(**PLOTLY_THEME, xaxis_tickangle=-45)
        st.plotly_chart(fig, use_container_width=True)

        # 5. Distribution box plot
        st.markdown('<div class="section-header">📦 Transaction Amount Distribution by Type</div>', unsafe_allow_html=True)
        fig = px.box(agg_txn, x="Transaction_Type", y="Transaction_Amount",
                     color="Transaction_Type",
                     color_discrete_sequence=["#a855f7","#7c3aed","#c084fc","#6d28d9","#d8b4fe"])
        fig.update_layout(**PLOTLY_THEME)
        st.plotly_chart(fig, use_container_width=True)


# ─────────────────────────────────────────────────────────────
#  PAGE: USERS
# ─────────────────────────────────────────────────────────────
elif page == "👥 Users":
    st.markdown("# 👥 User Analysis")
    agg_usr = apply_filters(load("aggregated_user"))
    map_usr = apply_filters(load("map_user"))

    if agg_usr.empty:
        st.warning("No user data found.")
    else:
        col1,col2 = st.columns(2)
        with col1:
            st.markdown('<div class="section-header">📈 Registered Users Growth</div>', unsafe_allow_html=True)
            users_yr = agg_usr.groupby("Year")["Registered_Users"].sum().reset_index()
            fig = px.area(users_yr, x="Year", y="Registered_Users",
                          color_discrete_sequence=["#a855f7"])
            fig.update_layout(**PLOTLY_THEME)
            st.plotly_chart(fig, use_container_width=True)
        with col2:
            st.markdown('<div class="section-header">📱 App Opens by Quarter</div>', unsafe_allow_html=True)
            app_q = agg_usr.groupby(["Year","Quarter"])["App_Opens"].sum().reset_index()
            app_q["Period"] = app_q["Year"].astype(str)+" Q"+app_q["Quarter"].astype(str)
            fig = px.bar(app_q.sort_values("Period"), x="Period", y="App_Opens",
                         color="App_Opens", color_continuous_scale="Purples")
            fig.update_layout(**PLOTLY_THEME, xaxis_tickangle=-45)
            st.plotly_chart(fig, use_container_width=True)

        # Top states by users
        st.markdown('<div class="section-header">🏅 Top 15 States — Registered Users</div>', unsafe_allow_html=True)
        top_usr = agg_usr.groupby("State")["Registered_Users"].sum().nlargest(15).reset_index()
        fig = px.bar(top_usr, x="State", y="Registered_Users",
                     color="Registered_Users", color_continuous_scale="Purples")
        fig.update_layout(**PLOTLY_THEME, xaxis_tickangle=-35)
        st.plotly_chart(fig, use_container_width=True)

    if not map_usr.empty:
        st.markdown('<div class="section-header">🗺️ District-Level User Density (Top 20 Districts)</div>', unsafe_allow_html=True)
        dist_top = map_usr.groupby("District")["Registered_Users"].sum().nlargest(20).reset_index()
        fig = px.treemap(dist_top, path=["District"], values="Registered_Users",
                         color="Registered_Users", color_continuous_scale="Purples")
        fig.update_layout(**PLOTLY_THEME)
        st.plotly_chart(fig, use_container_width=True)


# ─────────────────────────────────────────────────────────────
#  PAGE: INSURANCE
# ─────────────────────────────────────────────────────────────
elif page == "🛡️ Insurance":
    st.markdown("# 🛡️ Insurance Analysis")
    agg_ins = apply_filters(load("aggregated_insurance"))
    map_ins = apply_filters(load("map_insurance"))

    if agg_ins.empty:
        st.info("Insurance data not present in the repository for your filters.")
    else:
        col1,col2 = st.columns(2)
        with col1:
            st.markdown('<div class="section-header">📊 Insurance by Type</div>', unsafe_allow_html=True)
            ins_type = agg_ins.groupby("Insurance_Type")["Transaction_Amount"].sum().reset_index()
            fig = px.pie(ins_type, names="Insurance_Type", values="Transaction_Amount",
                         hole=0.45, color_discrete_sequence=["#a855f7","#7c3aed","#c084fc","#6d28d9"])
            fig.update_layout(**PLOTLY_THEME)
            st.plotly_chart(fig, use_container_width=True)
        with col2:
            st.markdown('<div class="section-header">📈 Insurance Volume Growth</div>', unsafe_allow_html=True)
            ins_yr = agg_ins.groupby("Year")["Transaction_Amount"].sum().reset_index()
            fig = px.area(ins_yr, x="Year", y="Transaction_Amount",
                          color_discrete_sequence=["#c084fc"])
            fig.update_layout(**PLOTLY_THEME)
            st.plotly_chart(fig, use_container_width=True)

        st.markdown('<div class="section-header">🏆 Top 10 States — Insurance Value</div>', unsafe_allow_html=True)
        top_ins = agg_ins.groupby("State")["Transaction_Amount"].sum().nlargest(10).reset_index()
        fig = px.funnel(top_ins, x="Transaction_Amount", y="State",
                        color_discrete_sequence=["#a855f7"])
        fig.update_layout(**PLOTLY_THEME)
        st.plotly_chart(fig, use_container_width=True)


# ─────────────────────────────────────────────────────────────
#  PAGE: GEO MAPS
# ─────────────────────────────────────────────────────────────
elif page == "🗺️ Geo Maps":
    st.markdown("# 🗺️ Geo-Spatial Analysis")
    agg_txn = apply_filters(load("aggregated_transaction"))
    map_txn = apply_filters(load("map_transaction"))

    # State-level choropleth
    if not agg_txn.empty:
        st.markdown('<div class="section-header">India State-Level Transaction Value</div>', unsafe_allow_html=True)
        state_agg = agg_txn.groupby("State").agg(
            Amount=("Transaction_Amount","sum"),
            Count=("Transaction_Count","sum")
        ).reset_index()

        metric = st.radio("Metric", ["Amount","Count"], horizontal=True)
        fig = px.choropleth(
            state_agg,
            geojson="https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson",
            featureidkey="properties.ST_NM",
            locations="State",
            color=metric,
            color_continuous_scale="Purples",
            title=f"State-Level Transaction {metric}",
        )
        fig.update_geos(fitbounds="locations", visible=False)
        fig.update_layout(**PLOTLY_THEME, height=600)
        st.plotly_chart(fig, use_container_width=True)

    # District scatter
    if not map_txn.empty:
        st.markdown('<div class="section-header">District-Level Bubble Chart</div>', unsafe_allow_html=True)
        dist_agg = map_txn.groupby(["State","District"]).agg(
            Amount=("Transaction_Amount","sum"),
            Count=("Transaction_Count","sum")
        ).reset_index()
        fig = px.scatter(dist_agg, x="Count", y="Amount", size="Amount",
                         color="State", hover_name="District",
                         color_discrete_sequence=px.colors.qualitative.Plotly,
                         title="District: Transaction Count vs Amount")
        fig.update_layout(**PLOTLY_THEME)
        st.plotly_chart(fig, use_container_width=True)


# ─────────────────────────────────────────────────────────────
#  PAGE: TOP PERFORMERS
# ─────────────────────────────────────────────────────────────
elif page == "🏆 Top Performers":
    st.markdown("# 🏆 Top Performers")

    tab1, tab2, tab3 = st.tabs(["Districts","Pincodes","User Districts"])

    with tab1:
        df = apply_filters(load("top_transaction_district"))
        if not df.empty:
            top_dist = df.groupby("District")["Transaction_Amount"].sum().nlargest(15).reset_index()
            fig = px.bar(top_dist, x="Transaction_Amount", y="District", orientation="h",
                         color="Transaction_Amount", color_continuous_scale="Purples",
                         title="Top 15 Districts by Transaction Amount")
            fig.update_layout(**PLOTLY_THEME, height=500)
            st.plotly_chart(fig, use_container_width=True)

    with tab2:
        df = apply_filters(load("top_transaction_pincode"))
        if not df.empty:
            top_pin = df.groupby("Pincode")["Transaction_Amount"].sum().nlargest(15).reset_index()
            top_pin["Pincode"] = top_pin["Pincode"].astype(str)
            fig = px.bar(top_pin, x="Transaction_Amount", y="Pincode", orientation="h",
                         color="Transaction_Amount", color_continuous_scale="Purples",
                         title="Top 15 Pincodes by Transaction Amount")
            fig.update_layout(**PLOTLY_THEME, height=500)
            st.plotly_chart(fig, use_container_width=True)

    with tab3:
        df = apply_filters(load("top_user_district"))
        if not df.empty:
            top_ud = df.groupby("District")["Registered_Users"].sum().nlargest(15).reset_index()
            fig = px.bar(top_ud, x="Registered_Users", y="District", orientation="h",
                         color="Registered_Users", color_continuous_scale="Purples",
                         title="Top 15 Districts by Registered Users")
            fig.update_layout(**PLOTLY_THEME, height=500)
            st.plotly_chart(fig, use_container_width=True)


# ─────────────────────────────────────────────────────────────
#  PAGE: TREND ANALYSIS
# ─────────────────────────────────────────────────────────────
elif page == "📈 Trend Analysis":
    st.markdown("# 📈 Trend Analysis")
    agg_txn = apply_filters(load("aggregated_transaction"))
    agg_usr = apply_filters(load("aggregated_user"))

    if not agg_txn.empty:
        agg_txn["Period"] = agg_txn["Year"].astype(str)+" Q"+agg_txn["Quarter"].astype(str)
        period_df = agg_txn.groupby("Period").agg(
            Amount=("Transaction_Amount","sum"),
            Count=("Transaction_Count","sum")
        ).reset_index().sort_values("Period")

        st.markdown('<div class="section-header">📉 Transaction Volume Over Time</div>', unsafe_allow_html=True)
        fig = px.line(period_df, x="Period", y="Amount", markers=True,
                      color_discrete_sequence=["#a855f7"], title="Total Transaction Amount per Quarter")
        fig.update_layout(**PLOTLY_THEME, xaxis_tickangle=-45)
        st.plotly_chart(fig, use_container_width=True)

        # Growth rate
        st.markdown('<div class="section-header">📊 Quarter-over-Quarter Growth Rate</div>', unsafe_allow_html=True)
        period_df["Growth_Rate"] = period_df["Amount"].pct_change() * 100
        fig = px.bar(period_df.dropna(), x="Period", y="Growth_Rate",
                     color="Growth_Rate",
                     color_continuous_scale="RdBu",
                     title="QoQ Growth Rate (%)")
        fig.add_hline(y=0, line_dash="dash", line_color="white")
        fig.update_layout(**PLOTLY_THEME, xaxis_tickangle=-45)
        st.plotly_chart(fig, use_container_width=True)

    if not agg_usr.empty:
        st.markdown('<div class="section-header">👤 Users vs App Engagement</div>', unsafe_allow_html=True)
        usr_period = agg_usr.copy()
        usr_period["Period"] = usr_period["Year"].astype(str)+" Q"+usr_period["Quarter"].astype(str)
        usr_trend = usr_period.groupby("Period").agg(
            Users=("Registered_Users","sum"),
            Opens=("App_Opens","sum")
        ).reset_index().sort_values("Period")
        fig = make_subplots(specs=[[{"secondary_y": True}]])
        fig.add_trace(go.Bar(x=usr_trend["Period"], y=usr_trend["Users"],
                             name="Registered Users", marker_color="#7c3aed"), secondary_y=False)
        fig.add_trace(go.Scatter(x=usr_trend["Period"], y=usr_trend["Opens"],
                                 name="App Opens", line=dict(color="#f5d0fe",width=2), mode="lines+markers"), secondary_y=True)
        fig.update_layout(title="Users vs App Opens Trend", **PLOTLY_THEME, xaxis_tickangle=-45)
        st.plotly_chart(fig, use_container_width=True)

    # --- Correlation heatmap ---
    if not agg_txn.empty and not agg_usr.empty:
        st.markdown('<div class="section-header">🔗 Correlation Matrix</div>', unsafe_allow_html=True)
        corr_df = agg_txn.groupby("State").agg(
            Txn_Amount=("Transaction_Amount","sum"),
            Txn_Count=("Transaction_Count","sum")).reset_index()
        usr_state = agg_usr.groupby("State").agg(
            Users=("Registered_Users","sum"),
            App_Opens=("App_Opens","sum")).reset_index()
        merged = corr_df.merge(usr_state, on="State", how="inner")
        corr = merged[["Txn_Amount","Txn_Count","Users","App_Opens"]].corr()
        fig = px.imshow(corr, text_auto=".2f", color_continuous_scale="Purples",
                        title="Correlation: Transactions vs User Engagement")
        fig.update_layout(**PLOTLY_THEME)
        st.plotly_chart(fig, use_container_width=True)

# Footer
st.markdown("---")
st.markdown("<center style='color:#7c3aed;'>📱 PhonePe Transaction Insights | Labmentix Internship Project</center>",
            unsafe_allow_html=True)
